/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package poli;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-11-12")
public class NoEncontrado extends org.apache.thrift.TException implements org.apache.thrift.TBase<NoEncontrado, NoEncontrado._Fields>, java.io.Serializable, Cloneable, Comparable<NoEncontrado> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NoEncontrado");

  private static final org.apache.thrift.protocol.TField DATO_FIELD_DESC = new org.apache.thrift.protocol.TField("dato", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new NoEncontradoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new NoEncontradoTupleSchemeFactory();

  public java.lang.String dato; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DATO((short)1, "dato");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATO
          return DATO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATO, new org.apache.thrift.meta_data.FieldMetaData("dato", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NoEncontrado.class, metaDataMap);
  }

  public NoEncontrado() {
  }

  public NoEncontrado(
    java.lang.String dato)
  {
    this();
    this.dato = dato;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NoEncontrado(NoEncontrado other) {
    if (other.isSetDato()) {
      this.dato = other.dato;
    }
  }

  public NoEncontrado deepCopy() {
    return new NoEncontrado(this);
  }

  @Override
  public void clear() {
    this.dato = null;
  }

  public java.lang.String getDato() {
    return this.dato;
  }

  public NoEncontrado setDato(java.lang.String dato) {
    this.dato = dato;
    return this;
  }

  public void unsetDato() {
    this.dato = null;
  }

  /** Returns true if field dato is set (has been assigned a value) and false otherwise */
  public boolean isSetDato() {
    return this.dato != null;
  }

  public void setDatoIsSet(boolean value) {
    if (!value) {
      this.dato = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DATO:
      if (value == null) {
        unsetDato();
      } else {
        setDato((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DATO:
      return getDato();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DATO:
      return isSetDato();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof NoEncontrado)
      return this.equals((NoEncontrado)that);
    return false;
  }

  public boolean equals(NoEncontrado that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_dato = true && this.isSetDato();
    boolean that_present_dato = true && that.isSetDato();
    if (this_present_dato || that_present_dato) {
      if (!(this_present_dato && that_present_dato))
        return false;
      if (!this.dato.equals(that.dato))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDato()) ? 131071 : 524287);
    if (isSetDato())
      hashCode = hashCode * 8191 + dato.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(NoEncontrado other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDato()).compareTo(other.isSetDato());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDato()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dato, other.dato);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("NoEncontrado(");
    boolean first = true;

    sb.append("dato:");
    if (this.dato == null) {
      sb.append("null");
    } else {
      sb.append(this.dato);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NoEncontradoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NoEncontradoStandardScheme getScheme() {
      return new NoEncontradoStandardScheme();
    }
  }

  private static class NoEncontradoStandardScheme extends org.apache.thrift.scheme.StandardScheme<NoEncontrado> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NoEncontrado struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DATO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dato = iprot.readString();
              struct.setDatoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NoEncontrado struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dato != null) {
        oprot.writeFieldBegin(DATO_FIELD_DESC);
        oprot.writeString(struct.dato);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NoEncontradoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NoEncontradoTupleScheme getScheme() {
      return new NoEncontradoTupleScheme();
    }
  }

  private static class NoEncontradoTupleScheme extends org.apache.thrift.scheme.TupleScheme<NoEncontrado> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NoEncontrado struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDato()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetDato()) {
        oprot.writeString(struct.dato);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NoEncontrado struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.dato = iprot.readString();
        struct.setDatoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

